update scripts, nvim

diff --git a/scripts/stilux/users/screenshot b/scripts/stilux/users/screenshot
--- a/scripts/stilux/users/screenshot
+++ b/scripts/stilux/users/screenshot
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # The scripts is wtitten by Tran Vo Son Tung
 # Screenshot scripts
 # Dependencies: scrot, xclip, dunstify
@@ -7,38 +7,54 @@
 # select-clipboard: select an area and copy it to the select-clipboard
 # window: capture the focused window and save it to the directory
 
-help() {
-	echo " This script is written by Tran Vo Son Tung"
-	echo " Dependencies: scrot, xclip, dunstify"
-	printf "\nUSAGE: screenshot [OPTIONS] [FUNCTION]\n"
-	printf "\nOPTIONS:\n"
-	echo "  -h, --help           show help"
-	printf "\nFUNCTION:\n"
-	echo "  select-save          select an area and save it to the directory"
-	echo "  select-clipboard     select an area and copy it to the select-clipboard"
-	echo "  window               capture the focused window and save it to the directory"
-	echo "  NOTE: The default function of scrot can use to capture the screen"
+NO='\033[0m' # No Color
+BLUE='\033[1;34m'
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+
+display_help() {
+	echo -e "${BLUE}INFORMATION:${NO}"
+	echo -e "  This script is written by Tran Vo Son Tung"
+	echo -e "  Dependencies: scrot, xclip, dunstify"
+	echo -e "  USAGE: screenshot [OPTIONS] [FUNCTION]\n"
+
+	echo -e "${BLUE}OPTIONS:${NO}"
+	echo -e "  -h, --help           show help\n"
+
+	echo -e "${BLUE}FUNCTION:${NO}"
+	echo -e "  select-save          select an area and save it to the directory"
+	echo -e "  select-clipboard     select an area and copy it to the select-clipboard"
+	echo -e "  window               capture the focused window and save it to the directory\n"
+
+	echo -e "${BLUE}EXAMPLES:${NO}"
+	echo -e "  screenshot select-save"
+	echo -e "  screenshot select-clipboard"
+	echo -e "  screenshot window"
+	echo -e "  screenshot --help"
+	echo -e "  screenshot -h"
+
 }
 
 # Show help if no arguments
 if [ "$#" -eq 0 ]; then
-	help
+	display_help
 	exit 0
 fi
 
 # Check if install scrot, xclip, dunstify
 if [ ! -x "$(command -v scrot)" ]; then
-	echo "Please install scrot to use this scripts"
+	echo -e "${RED}[ERROR]:${NO} Please install scrot to use this scripts"
 	exit 1
 fi
 
 if [ ! -x "$(command -v xclip)" ]; then
-	echo "please install xclip to use this scripts"
+	echo -e "${RED}[ERROR]:${NO} Please install xclip to use this scripts"
 	exit 1
 fi
 
 if [ ! -x "$(command -v dunstify)" ]; then
-	echo "please install dunst to use this scripts"
+	echo -e "${RED}[ERROR]:${NO} Please install dunst to use this scripts"
 	exit 1
 fi
 
@@ -50,9 +66,19 @@ output="/tmp/%F_%T_$wx$h.png"
 outputDir="$HOME/Pictures/Screenshots/%Y_%m_%d-%T-screentshot.png"
 
 case "$1" in
-"select-save") scrot "$outputDir" --select --line mode=edge -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit ;;
-"select-clipboard") scrot "$output" --select --line mode=edge -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Copy to clipboard" -i $f -a "scrot" && rm $f' || exit ;;
-"window") scrot "$outputDir" --focused --border -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit ;;
-"--help" | "-h") help ;;
-*) scrot "$outputDir" -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit ;;
+"select-save")
+	scrot "$outputDir" --select --line mode=edge -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit 1
+	;;
+"select-clipboard")
+	scrot "$output" --select --line mode=edge -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Copy to clipboard" -i $f -a "scrot" && rm $f' || exit 1
+	;;
+"window")
+	scrot "$outputDir" --focused --border -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit 1
+	;;
+"--help" | "-h")
+	display_help
+	;;
+*)
+	scrot "$outputDir" -e 'xclip -selection clipboard -target image/png -i $f && dunstify "Save $f" -i $f -a "scrot"' || exit 1
+	;;
 esac
